name: Build packages

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  check-flake:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-22.04
          # - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@V27

    - name: Flake metadata
      run: >
        nix flake metadata

    - name: Flake show
      run: >
        nix flake show

    - name: Flake check
      run: >
        nix flake check --no-build --accept-flake-config

  build-packages:
    needs: check-flake
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-22.04
          # - macos-11

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix
      uses: cachix/install-nix-action@V27

    - name: Setup cachix
      uses: cachix/cachix-action@v15
      with:
        name: geonix-rolling
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build all packages
      run: >
        nix build -L --accept-flake-config .#all-packages

    - name: Test cli shell
      run: >
        nix develop --accept-flake-config .#cli
        --command python -c "import fiona; print(fiona.supported_drivers)"

  list-updates:
    needs: build-packages
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: geonix-rolling
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: List updated packages
        run: >
          nix run --accept-flake-config nixpkgs/nixpkgs-unstable#nvd -- diff
          $(nix build github:imincik/geospatial-nix.repo/latest#all-packages --print-out-paths)
          $(nix build .#all-packages --print-out-paths) > $GITHUB_STEP_SUMMARY


# tests
  launch-test:
    needs: build-packages
    uses: ./.github/workflows/test.yml
    secrets: inherit

  launch-nixos-test:
    needs: build-packages
    uses: ./.github/workflows/nixos-test.yml
    secrets: inherit
